version: "3.8"
services:
  vpn-web:
    build: .
    container_name: openvpn-web
    ports:
      - "9192:9192"
    cap_add:
      - NET_ADMIN
    volumes:
      - vpn-jobs:/app/jobs
    restart: unless-stopped

volumes:
  vpn-jobs:
